### PR TITLE
Additional Installation Requirements

### PR DESCRIPTION
**Pull request by adamzvolanek**
Adding some text and comments to the `readme.md` and `docker-compose.yaml` file. Namely about the need to populate the `/data` directory with the items in the https://github.com/pbogre/jetlog/tree/main/data directory.

### CODE REVIEW

**Comment by pbogre** [comment]
Thanks for the PR! However, the files in the `data` directory from the repo are present in the docker image (see line 43 of `Dockerfile)`, so there's no need to also put them in the actual data directory that is mounted as a volume. You should be able to find these files in the running container at `/app/data`, if that's not the case, this is a problem I should fix.

**Comment by adamzvolanek** [comment]
> Thanks for the PR! However, the files in the `data` directory from the repo are present in the docker image (see line 43 of `Dockerfile)`, so there's no need to also put them in the actual data directory that is mounted as a volume. You should be able to find these files in the running container at `/app/data`, if that's not the case, this is a problem I should fix.

I went ahead and removed the appdata files:

```bash
Linux 6.1.99-Unraid.
root@dev-laptop:~# cd /mnt/user/appdata
root@dev-laptop:/mnt/user/appdata# ls
cloud/      core/       docs/    internal/
root@dev-laptop:/mnt/user/appdata# ls internal
jetlog/
root@dev-laptop:/mnt/user/appdata# rm -rf internal/jetlog
root@dev-laptop:/mnt/user/appdata# ls internal

```




However then fails out with the error mentioned here:

**Comment by pbogre** [comment]
Yeah unfortunately this is due to an ownership error in the volume your provided. Have a look at #5 for more details

**Comment by adepssimius** [comment]
I am having issues with this as well. Trying to run this as a non-root user security context in kubernetes fails with the default command since gosu needs to be run as root. I don't like to allow containers to run with the root user if they don't need to.

If I set the security context user as nonroot, then gosu fails. If I set the security context user as root so gosu will work (again not my favorite), then the volume owner is set to root and I can't get the DB to create. I don't have other options that I know of.

**Comment by pbogre** [comment]
I see that you opened and closed an issue about this problem (#30). Does this mean it's no longer a problem, or should I still look into this? 

If the container cannot start as non-root, I see that as a problem. I'll open an issue about that so we can move this discussion there.

**Comment by adepssimius** [comment]
I didn't intended that other issue to be an actual issue, I was looking for a quick way to provide a k8s starting point for others based on my working with the container. Indeed, I could not get non-root to work with your entry point since gosu must be run as root.

**Pull request closed without merging**
