### PR TITLE
User authentication and different accounts

### LINKED ISSUE #26: Add option to record flights for more than one user
it would be nice to be able to mark that one of my kids or my wife took a flight as well, or even proper user account support (think OIDC, not local auth).

not that I'm ungrateful for this awesome tracking tool already, I'm just listing off my "this would be nice" list since I share the passion for data tracking and aviation :)

### LINKED ISSUE #43: User authentication
Add the ability to set a user name and password which would then be required to access Jetlog through a custom login page.

Required for #26

### PR DESCRIPTION
**Pull request by pbogre**
Closes #43
Closes #26

This pull request aims to implement OAuth2 authentication ([FastAPI docs](https://fastapi.tiangolo.com/tutorial/security/oauth2-jwt/)) by implementing the following functionality:

- [x] `users` database table
- [x] Token creation & authentication
- [x] Ability to create, delete, and update users
- [x] Restrict Jetlog access to authenticated users
- [x] Login page
- [x] Add user field to flights
- [x] Personalized view of Jetlog based on user (i.e., each user sees their own flights)
- [x] User management settings for administrators (create/edit/delete users)
- [x] User management settings for users (edit own username/password) 
- [x] Endpoint to delete users and all their flights
- [x] Ability to access other users' flights
- [x] Get `SECRET_KEY` from (docker) environment
- [x] Full backward compatibility (put all flights on first user)

### CODE REVIEW

**Comment by pbogre** [comment]
Note that currently this is UNSAFE, since the `SECRET_KEY` variable is fixed.

Currently there is an issue where if you update your own username, your credentials will no longer be valid. To fix this I could update the token automatically when this occurs (?).

For anyone who wants to test this, the default user has username `admin` and password `admin`, and it is created once Jetlog is started and the `users` table is created.

Note that, so far, this change can only really be tested in the Swagger docs of Jetlog (automatically generated in `0.0.0.0:3000/docs`). The ability to create and edit users is there, but it needs to be refined.

**Comment by pbogre** [comment]
The latest commit supports a very basic but functional authentication system, which allows only authenticated users to access Jetlog. Next, each user should have a personalized view of Jetlog with only the flights/data relevant to them.

The current state of the code is somewhat janky, and some things that I need to work on next are:
- Don't redirect to the login page on failed login attempts (instead, notify that credentials are wrong)
- Don't redirect on Unauthorized requests using `window.location.href = "/login"`
- Hidden characters in password input
- Improve look of login page
- Logout option in settings (maybe even more accessible? how?)

As progress for this feature moves forward, I am realizing that there are quite a few aspects of the code that I would like to change, for example:
- The settings page should undergo a complete rework, with tab-based settings instead of a bunch of containers
- The code of the class for client-side API calls is quite ugly (`api.ts`)




If anyone is reading this, I apologize for the long wait on this feature. I have been quite busy lately, and I don't see that changing very soon, which unfortunately means that updates will keep coming out at a slow rate. I'm doing my best to find the time to work on Jetlog.

**Comment by pbogre** [comment]
Aside from user management for admins, the bare functionality of this feature has mostly been implemented. Users are now able to log in and view/edit/delete/create ONLY their flights. 

Some things missing from the latest commits, aside from UI improvements, are:
- UI for admins to create/delete/edit users
- UI for users to update own username/password
- UI to log out

**Comment by pbogre** [comment]
Something I need to decide is how to handle the creation of the first user. Currently the first user is created by default and has username and password `admin`. This could be fine, but perhaps a better way of doing this is that, when there are no users in the `users` table, the first login is handled as an admin account creation. The user would of course have to be notified that since this is their first login, they are creating an account.

**Comment by pbogre** [comment]
Reminder to self: remove "Edit" and "Delete" buttons for normal (non-admin) users viewing someone else's flight

**Comment by pbogre** [comment]
The first complete version of this branch is now available with the `:experimental` docker tag. If anyone wishes to try this, feel free to pull that image. I am going to do some tests to make sure it works before releasing it. 🎉

**Comment by adepssimius** [comment]
Congrats on the milestone and thank you! 

Are you planning on a graceful upgrade path from "experimental" to the released version? I'm ok tossing my data at this point but it would be nice if I didn't have to.

**Comment by pbogre** [comment]
Thanks @adepssimius!

Currently upgrading version from pre-auth will simply create the new default user (admin:admin) and assign all previous flights to that user. As far as I have tested this works, which means you won't have to scrap all of your data :)

**Pull request merged**
