### PR TITLE
Add aircraft side option

### PR DESCRIPTION
**Pull request by adepssimius**
It would be nice to be able to record where I was sitting on a plane, for instance to correlate particular views of geography with the side of the plane that I need to be on to see it.

I'm not 100% happy with the name "Seat Location", since I feel like it could get easily confused with seat type. I considered the term "Plane Side", but that seems to exclude the center seats on widebody aircraft. Maybe that would still be a better name.

I think I got everything I needed to update, but I am neither a python expert nor a front end dev.

Thoughts?

### CODE REVIEW

**Comment by pbogre** [comment]
Thanks for the suggestion and PR! I like the idea of recording the side of the plane one was sitting in. I ran the application myself and everything seems to work, however there is an issue with your changes in `importing.py` for MyFlightRadar24 CSV's, because they do not have a "Seat Location" attribute, and I don't think that's something they record at all.

Other than that, I think it's good. We could rename the "Seat Location" to something else to avoid confusion with `SeatType`; perhaps `AircraftSide`, `WingSide`, `PlaneSide`? I think `SeatLocation` makes it sound like it should be the seat number that you get, like B20, not the side of the plane you were sitting in.

**Comment by adepssimius** [comment]
I updated to use aircraft side instead of seat location. I agree that seat location was a poor name.

**Comment by adepssimius** [comment]
Thanks for taking care of the importing. I wasn't sure where the source of the CSV to import was and I meant to go update wherever the template was stored later but I guess if it's coming from FR24 then that would be more difficult than I thought 😆

**Comment by pbogre** [comment]
Thanks for the changes. I am going to test this change a bit more before I merge.

No worries about the FR24, and thanks again for the PR :)

**Pull request merged**
